version: '3.8'

services:
# container for the PostgreSQL 
  postgres:
    image: postgres:15
    container_name: electromart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: electromart
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app-network
# container for the  fronetend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: electromart-frontend
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND: http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
      # container for the backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: electromart-backend
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: electromart
      NODE_ENV: development
      JWT_SECRET: your_jwt_secret
    ports:
      - "8080:8080" 
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: